services:
  - type: web
    name: laravel-react-gamecenter
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_URL
        value: https://laravel-react-gamecenter.onrender.com
      - key: ASSET_URL
        value: https://laravel-react-gamecenter.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-1-ap-southeast-1.pooler.supabase.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.qfsbuysynkzbuwltqqrk
      - key: DB_PASSWORD
        sync: false
